$(document).ready(function(){
    $('.owl-carousel').owlCarousel({
        loop:true,
        center: true,
        margin:10,
        nav:true,
        autoplay:false,
        responsive:{
            0:{
                items:1
            },
            600:{
                items:2
            },
            1000:{
                items:3
            }
        }
    })
  });